In [12]:
import torch

In [13]:
tens08 = torch.Size([3,2,1,1])
tens08

torch.Size([3, 2, 1, 1])

In [14]:
tens09 = torch.rand(6)
tens09
tens08 = tens09.reshape(3,2,1,1)
tens08

tensor([[[[0.7719]],

         [[0.1253]]],


        [[[0.9935]],

         [[0.5273]]],


        [[[0.5723]],

         [[0.7309]]]])

In [15]:
tens08 = tens09.reshape(3,2,1,1,)

In [16]:
tens10 = torch.rand(5,1)
tens11 = torch.rand(1,4)

In [17]:
print(tens10)
print(tens11)

tensor([[0.8959],
        [0.0270],
        [0.4715],
        [0.6062],
        [0.9584]])
tensor([[0.0430, 0.1185, 0.0925, 0.2788]])


In [18]:
points = torch.rand(10,2)

In [19]:
points

tensor([[0.7023, 0.4500],
        [0.6021, 0.6220],
        [0.9408, 0.7037],
        [0.9694, 0.5294],
        [0.1654, 0.8048],
        [0.3792, 0.4253],
        [0.8643, 0.9275],
        [0.9936, 0.2629],
        [0.8678, 0.7321],
        [0.8282, 0.7031]])

In [20]:
points.shape[0]

10

In [21]:
# for i in range(points.shape[0]):
#     for j in range(points.shape[0]):
#         dist[i,j] = (points[i] - points[j]).pow(2).sum()

In [22]:
tens12 = torch.rand(24).reshape(3,4,2)

In [23]:
tens12

tensor([[[0.8911, 0.7002],
         [0.9918, 0.6856],
         [0.2080, 0.3744],
         [0.5683, 0.6498]],

        [[0.4853, 0.4590],
         [0.7405, 0.7826],
         [0.9588, 0.1717],
         [0.3941, 0.9245]],

        [[0.0667, 0.6787],
         [0.8040, 0.9987],
         [0.5642, 0.8349],
         [0.0908, 0.4660]]])

In [24]:
points[:,None,:].shape

torch.Size([10, 1, 2])

In [25]:
points[None,:,:].shape

torch.Size([1, 10, 2])

In [26]:
tens12

tensor([[[0.8911, 0.7002],
         [0.9918, 0.6856],
         [0.2080, 0.3744],
         [0.5683, 0.6498]],

        [[0.4853, 0.4590],
         [0.7405, 0.7826],
         [0.9588, 0.1717],
         [0.3941, 0.9245]],

        [[0.0667, 0.6787],
         [0.8040, 0.9987],
         [0.5642, 0.8349],
         [0.0908, 0.4660]]])

In [27]:
tens12.shape

torch.Size([3, 4, 2])

In [28]:
tens13 = tens12.reshape(12,2)

In [29]:
tens13

tensor([[0.8911, 0.7002],
        [0.9918, 0.6856],
        [0.2080, 0.3744],
        [0.5683, 0.6498],
        [0.4853, 0.4590],
        [0.7405, 0.7826],
        [0.9588, 0.1717],
        [0.3941, 0.9245],
        [0.0667, 0.6787],
        [0.8040, 0.9987],
        [0.5642, 0.8349],
        [0.0908, 0.4660]])

In [30]:
tens14= tens13[None,:,:]
tens14

tensor([[[0.8911, 0.7002],
         [0.9918, 0.6856],
         [0.2080, 0.3744],
         [0.5683, 0.6498],
         [0.4853, 0.4590],
         [0.7405, 0.7826],
         [0.9588, 0.1717],
         [0.3941, 0.9245],
         [0.0667, 0.6787],
         [0.8040, 0.9987],
         [0.5642, 0.8349],
         [0.0908, 0.4660]]])

In [31]:
tens15= tens13[:,None,:]
tens15

tensor([[[0.8911, 0.7002]],

        [[0.9918, 0.6856]],

        [[0.2080, 0.3744]],

        [[0.5683, 0.6498]],

        [[0.4853, 0.4590]],

        [[0.7405, 0.7826]],

        [[0.9588, 0.1717]],

        [[0.3941, 0.9245]],

        [[0.0667, 0.6787]],

        [[0.8040, 0.9987]],

        [[0.5642, 0.8349]],

        [[0.0908, 0.4660]]])

In [32]:
tens14-tens15

tensor([[[ 0.0000,  0.0000],
         [ 0.1007, -0.0146],
         [-0.6831, -0.3258],
         [-0.3228, -0.0504],
         [-0.4058, -0.2412],
         [-0.1506,  0.0824],
         [ 0.0677, -0.5285],
         [-0.4970,  0.2243],
         [-0.8244, -0.0216],
         [-0.0871,  0.2985],
         [-0.3269,  0.1347],
         [-0.8003, -0.2343]],

        [[-0.1007,  0.0146],
         [ 0.0000,  0.0000],
         [-0.7838, -0.3112],
         [-0.4235, -0.0358],
         [-0.5065, -0.2266],
         [-0.2513,  0.0970],
         [-0.0330, -0.5139],
         [-0.5977,  0.2389],
         [-0.9251, -0.0070],
         [-0.1878,  0.3131],
         [-0.4276,  0.1493],
         [-0.9010, -0.2197]],

        [[ 0.6831,  0.3258],
         [ 0.7838,  0.3112],
         [ 0.0000,  0.0000],
         [ 0.3603,  0.2755],
         [ 0.2773,  0.0846],
         [ 0.5325,  0.4082],
         [ 0.7508, -0.2027],
         [ 0.1861,  0.5501],
         [-0.1413,  0.3043],
         [ 0.5960,  0.6243],
         [

In [33]:
tensa1 = torch.rand(5,2)

In [34]:
tensa2=tensa1

In [35]:
tensa1

tensor([[0.8729, 0.3924],
        [0.1870, 0.7491],
        [0.2302, 0.6981],
        [0.5014, 0.8800],
        [0.2939, 0.6440]])

In [36]:
tensa1 - tensa2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [37]:
2245/45

49.888888888888886

In [38]:
(2245+175)/46

52.608695652173914

In [39]:
2697/65

41.49230769230769

In [40]:
(2697+129)/65

43.47692307692308

In [41]:
dist = torch.zeros(12,12)
dist = (tens14-tens15).pow(2).sum(-1)
print(dist)


tensor([[0.0000, 0.0104, 0.5728, 0.1067, 0.2228, 0.0295, 0.2839, 0.2973, 0.6801,
         0.0967, 0.1250, 0.6953],
        [0.0104, 0.0000, 0.7112, 0.1806, 0.3079, 0.0726, 0.2652, 0.4143, 0.8559,
         0.1333, 0.2051, 0.8600],
        [0.5728, 0.7112, 0.0000, 0.2057, 0.0841, 0.4502, 0.6048, 0.3372, 0.1125,
         0.7449, 0.3390, 0.0221],
        [0.1067, 0.1806, 0.2057, 0.0000, 0.0433, 0.0473, 0.3811, 0.1058, 0.2525,
         0.1772, 0.0343, 0.2618],
        [0.2228, 0.3079, 0.0841, 0.0433, 0.0000, 0.1698, 0.3068, 0.2250, 0.2234,
         0.3928, 0.1475, 0.1556],
        [0.0295, 0.0726, 0.4502, 0.0473, 0.1698, 0.0000, 0.4209, 0.1401, 0.4648,
         0.0507, 0.0338, 0.5223],
        [0.2839, 0.2652, 0.6048, 0.3811, 0.3068, 0.4209, 0.0000, 0.8856, 1.0528,
         0.7079, 0.5956, 0.8400],
        [0.2973, 0.4143, 0.3372, 0.1058, 0.2250, 0.1401, 0.8856, 0.0000, 0.1676,
         0.1735, 0.0370, 0.3022],
        [0.6801, 0.8559, 0.1125, 0.2525, 0.2234, 0.4648, 1.0528, 0.1676, 0.0000,

In [42]:
d = torch.zeros(12,12)
for i in range(12):
    for j in range(12):
        d[i,j] = (tens13[i] - tens13[j]).pow(2).sum()
print(d)

tensor([[0.0000, 0.0104, 0.5728, 0.1067, 0.2228, 0.0295, 0.2839, 0.2973, 0.6801,
         0.0967, 0.1250, 0.6953],
        [0.0104, 0.0000, 0.7112, 0.1806, 0.3079, 0.0726, 0.2652, 0.4143, 0.8559,
         0.1333, 0.2051, 0.8600],
        [0.5728, 0.7112, 0.0000, 0.2057, 0.0841, 0.4502, 0.6048, 0.3372, 0.1125,
         0.7449, 0.3390, 0.0221],
        [0.1067, 0.1806, 0.2057, 0.0000, 0.0433, 0.0473, 0.3811, 0.1058, 0.2525,
         0.1772, 0.0343, 0.2618],
        [0.2228, 0.3079, 0.0841, 0.0433, 0.0000, 0.1698, 0.3068, 0.2250, 0.2234,
         0.3928, 0.1475, 0.1556],
        [0.0295, 0.0726, 0.4502, 0.0473, 0.1698, 0.0000, 0.4209, 0.1401, 0.4648,
         0.0507, 0.0338, 0.5223],
        [0.2839, 0.2652, 0.6048, 0.3811, 0.3068, 0.4209, 0.0000, 0.8856, 1.0528,
         0.7079, 0.5956, 0.8400],
        [0.2973, 0.4143, 0.3372, 0.1058, 0.2250, 0.1401, 0.8856, 0.0000, 0.1676,
         0.1735, 0.0370, 0.3022],
        [0.6801, 0.8559, 0.1125, 0.2525, 0.2234, 0.4648, 1.0528, 0.1676, 0.0000,

In [43]:
tens15[-1]

tensor([[0.0908, 0.4660]])

In [44]:
tens15

tensor([[[0.8911, 0.7002]],

        [[0.9918, 0.6856]],

        [[0.2080, 0.3744]],

        [[0.5683, 0.6498]],

        [[0.4853, 0.4590]],

        [[0.7405, 0.7826]],

        [[0.9588, 0.1717]],

        [[0.3941, 0.9245]],

        [[0.0667, 0.6787]],

        [[0.8040, 0.9987]],

        [[0.5642, 0.8349]],

        [[0.0908, 0.4660]]])

In [45]:
tens16 = (tens14 - tens15).pow(2)

In [46]:
tens16.shape

torch.Size([12, 12, 2])

In [47]:
tens16

tensor([[[0.0000e+00, 0.0000e+00],
         [1.0143e-02, 2.1322e-04],
         [4.6661e-01, 1.0616e-01],
         [1.0417e-01, 2.5372e-03],
         [1.6467e-01, 5.8166e-02],
         [2.2682e-02, 6.7870e-03],
         [4.5841e-03, 2.7934e-01],
         [2.4703e-01, 5.0296e-02],
         [6.7962e-01, 4.6485e-04],
         [7.5894e-03, 8.9093e-02],
         [1.0685e-01, 1.8148e-02],
         [6.4042e-01, 5.4881e-02]],

        [[1.0143e-02, 2.1322e-04],
         [0.0000e+00, 0.0000e+00],
         [6.1434e-01, 9.6859e-02],
         [1.7932e-01, 1.2794e-03],
         [2.5655e-01, 5.1336e-02],
         [6.3160e-02, 9.4061e-03],
         [1.0895e-03, 2.6412e-01],
         [3.5728e-01, 5.7059e-02],
         [8.5582e-01, 4.8421e-05],
         [3.5280e-02, 9.8023e-02],
         [1.8283e-01, 2.2296e-02],
         [8.1176e-01, 4.8253e-02]],

        [[4.6661e-01, 1.0616e-01],
         [6.1434e-01, 9.6859e-02],
         [0.0000e+00, 0.0000e+00],
         [1.2984e-01, 7.5875e-02],
         [7.6889

In [48]:
tens17 = tens16[0:1]

In [49]:
tens17.shape

torch.Size([1, 12, 2])

In [50]:
tens17 = tens17[:,0:3,:]

In [51]:
tens17

tensor([[[0.0000e+00, 0.0000e+00],
         [1.0143e-02, 2.1322e-04],
         [4.6661e-01, 1.0616e-01]]])

In [52]:
tens17.sum()


tensor(0.5831)

In [53]:
0.2749 + 0.2946 + 0.6035 + 0.0114

1.1844000000000001

In [54]:
tens17.sum(-1)

tensor([[0.0000, 0.0104, 0.5728]])

In [55]:
0.2749 + 0.2946

0.5694999999999999

In [56]:
0.6035 + 0.0114

0.6149

In [57]:
tens17[-1]

tensor([[0.0000e+00, 0.0000e+00],
        [1.0143e-02, 2.1322e-04],
        [4.6661e-01, 1.0616e-01]])

In [58]:
tens17

tensor([[[0.0000e+00, 0.0000e+00],
         [1.0143e-02, 2.1322e-04],
         [4.6661e-01, 1.0616e-01]]])

In [59]:
tens17.shape

torch.Size([1, 3, 2])

In [61]:
(tens17[-1]).shape

torch.Size([3, 2])

In [62]:
tensa1

tensor([[0.8729, 0.3924],
        [0.1870, 0.7491],
        [0.2302, 0.6981],
        [0.5014, 0.8800],
        [0.2939, 0.6440]])

In [64]:
asum = torch.zeros(5,1)
bsum = torch.zeros(1,2)
for i in range (5):
    for j in range (2):
        asum[i,0] = asum[i,0] + tensa1[i,j]
        bsum[0,j] = bsum[0,j] + tensa1[i,j]
print(asum)
print(bsum)

tensor([[1.2652],
        [0.9361],
        [0.9283],
        [1.3814],
        [0.9379]])
tensor([[2.0854, 3.3636]])


In [65]:
tensa1.sum(-1)

tensor([1.2652, 0.9361, 0.9283, 1.3814, 0.9379])

In [66]:
tensa1.sum(0)

tensor([2.0854, 3.3636])

In [67]:
15//4

3

In [68]:
17//4

4

In [69]:
17%4

1

In [70]:
tens16

tensor([[[0.0000e+00, 0.0000e+00],
         [1.0143e-02, 2.1322e-04],
         [4.6661e-01, 1.0616e-01],
         [1.0417e-01, 2.5372e-03],
         [1.6467e-01, 5.8166e-02],
         [2.2682e-02, 6.7870e-03],
         [4.5841e-03, 2.7934e-01],
         [2.4703e-01, 5.0296e-02],
         [6.7962e-01, 4.6485e-04],
         [7.5894e-03, 8.9093e-02],
         [1.0685e-01, 1.8148e-02],
         [6.4042e-01, 5.4881e-02]],

        [[1.0143e-02, 2.1322e-04],
         [0.0000e+00, 0.0000e+00],
         [6.1434e-01, 9.6859e-02],
         [1.7932e-01, 1.2794e-03],
         [2.5655e-01, 5.1336e-02],
         [6.3160e-02, 9.4061e-03],
         [1.0895e-03, 2.6412e-01],
         [3.5728e-01, 5.7059e-02],
         [8.5582e-01, 4.8421e-05],
         [3.5280e-02, 9.8023e-02],
         [1.8283e-01, 2.2296e-02],
         [8.1176e-01, 4.8253e-02]],

        [[4.6661e-01, 1.0616e-01],
         [6.1434e-01, 9.6859e-02],
         [0.0000e+00, 0.0000e+00],
         [1.2984e-01, 7.5875e-02],
         [7.6889

In [72]:
tens18 = tens16.sum(-1)

In [73]:
print(tens18.max(), (tens18.argmax()//12, tens18.argmax() %12))

tensor(1.0528) (tensor(6), tensor(8))


In [74]:
tens18

tensor([[0.0000, 0.0104, 0.5728, 0.1067, 0.2228, 0.0295, 0.2839, 0.2973, 0.6801,
         0.0967, 0.1250, 0.6953],
        [0.0104, 0.0000, 0.7112, 0.1806, 0.3079, 0.0726, 0.2652, 0.4143, 0.8559,
         0.1333, 0.2051, 0.8600],
        [0.5728, 0.7112, 0.0000, 0.2057, 0.0841, 0.4502, 0.6048, 0.3372, 0.1125,
         0.7449, 0.3390, 0.0221],
        [0.1067, 0.1806, 0.2057, 0.0000, 0.0433, 0.0473, 0.3811, 0.1058, 0.2525,
         0.1772, 0.0343, 0.2618],
        [0.2228, 0.3079, 0.0841, 0.0433, 0.0000, 0.1698, 0.3068, 0.2250, 0.2234,
         0.3928, 0.1475, 0.1556],
        [0.0295, 0.0726, 0.4502, 0.0473, 0.1698, 0.0000, 0.4209, 0.1401, 0.4648,
         0.0507, 0.0338, 0.5223],
        [0.2839, 0.2652, 0.6048, 0.3811, 0.3068, 0.4209, 0.0000, 0.8856, 1.0528,
         0.7079, 0.5956, 0.8400],
        [0.2973, 0.4143, 0.3372, 0.1058, 0.2250, 0.1401, 0.8856, 0.0000, 0.1676,
         0.1735, 0.0370, 0.3022],
        [0.6801, 0.8559, 0.1125, 0.2525, 0.2234, 0.4648, 1.0528, 0.1676, 0.0000,

In [2]:
import torch
matrix01 = torch.rand(2,3)
matrix01

tensor([[0.1086, 0.1659, 0.3214],
        [0.3018, 0.2341, 0.3782]])

In [3]:
matrix02 = torch.rand(3,2)
matrix02

tensor([[0.0609, 0.0971],
        [0.1621, 0.9042],
        [0.6573, 0.1391]])

In [4]:
matrix01 @ matrix02

tensor([[0.2447, 0.2053],
        [0.3049, 0.2936]])

In [5]:
print(torch.linalg.norm(matrix01))

tensor(0.6569)


In [6]:
matrix03 = torch.ones(3,2)
print(torch.linalg.norm(matrix03))

tensor(2.4495)


In [7]:
matrix03

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [8]:
6.sqrt()

SyntaxError: invalid syntax (2851005187.py, line 1)

In [9]:
sqrt(6)

NameError: name 'sqrt' is not defined

In [13]:
torch.sqrt(torch.Tensor([6]))

tensor([2.4495])

In [1]:
import torch.nn as nn

In [2]:
mod1 = nn.Linear(10,1)

In [3]:
mod1.weight

Parameter containing:
tensor([[ 0.0559, -0.2900, -0.1771, -0.2156, -0.1137, -0.0121,  0.3038, -0.0101,
         -0.0389,  0.0485]], requires_grad=True)

In [5]:
mod1.bias

Parameter containing:
tensor([-0.0528], requires_grad=True)

In [6]:
mod2 = nn.Linear(5,5)
mod2.bias

Parameter containing:
tensor([-0.3640, -0.0994, -0.1871, -0.2117, -0.4070], requires_grad=True)

In [8]:
import torch
data01 = torch.ones(10)
mod1(data01)

tensor([-0.5021], grad_fn=<AddBackward0>)