In [10]:
1 + 1

2

In [11]:
import torch

In [12]:
import torch.distributions as dist

In [13]:
bernoulli = dist.Bernoulli(torch.tensor([0.5]))

In [14]:
print(bernoulli.sample())

tensor([0.])


In [15]:
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))

In [16]:
print(normal.sample())

tensor([-0.5950])


In [17]:
for _ in range(10):
    print(normal.sample())

tensor([0.9377])
tensor([-1.6415])
tensor([0.0109])
tensor([-0.1305])
tensor([0.4112])
tensor([-0.3524])
tensor([-0.3072])
tensor([-0.4122])
tensor([-0.9826])
tensor([0.6418])


In [18]:
tens01 = torch.zeros(5)
tens01

tensor([0., 0., 0., 0., 0.])

In [19]:
tens02 = torch.ones(5)
tens02

tensor([1., 1., 1., 1., 1.])

In [20]:
tens03 = torch.rand(5)
tens03

tensor([0.5883, 0.6607, 0.8592, 0.9520, 0.8271])

In [21]:
tens04 = torch.rand(5,4)
tens04

tensor([[0.3296, 0.7726, 0.1612, 0.1193],
        [0.2952, 0.0316, 0.1167, 0.8351],
        [0.6014, 0.1781, 0.2489, 0.6977],
        [0.9652, 0.5266, 0.6623, 0.7642],
        [0.4070, 0.3332, 0.8123, 0.8646]])

In [22]:
tens04.view(5,2,2)

tensor([[[0.3296, 0.7726],
         [0.1612, 0.1193]],

        [[0.2952, 0.0316],
         [0.1167, 0.8351]],

        [[0.6014, 0.1781],
         [0.2489, 0.6977]],

        [[0.9652, 0.5266],
         [0.6623, 0.7642]],

        [[0.4070, 0.3332],
         [0.8123, 0.8646]]])

In [23]:
tens04

tensor([[0.3296, 0.7726, 0.1612, 0.1193],
        [0.2952, 0.0316, 0.1167, 0.8351],
        [0.6014, 0.1781, 0.2489, 0.6977],
        [0.9652, 0.5266, 0.6623, 0.7642],
        [0.4070, 0.3332, 0.8123, 0.8646]])

In [24]:
tens05 = tens04

In [25]:
tens05

tensor([[0.3296, 0.7726, 0.1612, 0.1193],
        [0.2952, 0.0316, 0.1167, 0.8351],
        [0.6014, 0.1781, 0.2489, 0.6977],
        [0.9652, 0.5266, 0.6623, 0.7642],
        [0.4070, 0.3332, 0.8123, 0.8646]])

In [26]:
tens06 = tens05.reshape(5,2,2)
tens06

tensor([[[0.3296, 0.7726],
         [0.1612, 0.1193]],

        [[0.2952, 0.0316],
         [0.1167, 0.8351]],

        [[0.6014, 0.1781],
         [0.2489, 0.6977]],

        [[0.9652, 0.5266],
         [0.6623, 0.7642]],

        [[0.4070, 0.3332],
         [0.8123, 0.8646]]])

In [27]:
tens07 = tens05.view(5,2,2)
tens07

tensor([[[0.3296, 0.7726],
         [0.1612, 0.1193]],

        [[0.2952, 0.0316],
         [0.1167, 0.8351]],

        [[0.6014, 0.1781],
         [0.2489, 0.6977]],

        [[0.9652, 0.5266],
         [0.6623, 0.7642]],

        [[0.4070, 0.3332],
         [0.8123, 0.8646]]])

In [28]:
tens05

tensor([[0.3296, 0.7726, 0.1612, 0.1193],
        [0.2952, 0.0316, 0.1167, 0.8351],
        [0.6014, 0.1781, 0.2489, 0.6977],
        [0.9652, 0.5266, 0.6623, 0.7642],
        [0.4070, 0.3332, 0.8123, 0.8646]])

In [29]:
print(tens05.ndim)
print(tens07.ndim)
print(tens05.dtype)
print(tens07.dtype)

2
3
torch.float32
torch.float32


In [30]:
from PIL import Image
import torch
import numpy as np 
cat01 = np.array(Image.open('cat.jpg'))
cat01 = torch.as_tensor(cat01)
cat01

tensor([[[ 74,  90, 126],
         [ 73,  89, 125],
         [ 74,  90, 126],
         ...,
         [ 69,  72,  51],
         [ 71,  74,  55],
         [ 76,  79,  60]],

        [[ 73,  89, 125],
         [ 73,  89, 125],
         [ 75,  91, 127],
         ...,
         [ 74,  77,  56],
         [ 79,  82,  63],
         [ 81,  84,  65]],

        [[ 75,  91, 127],
         [ 74,  90, 126],
         [ 76,  92, 128],
         ...,
         [ 81,  84,  63],
         [ 79,  82,  63],
         [ 79,  82,  63]],

        ...,

        [[ 73,  88, 131],
         [ 69,  84, 127],
         [ 70,  85, 128],
         ...,
         [123, 128, 106],
         [128, 133, 113],
         [129, 134, 114]],

        [[ 73,  88, 131],
         [ 70,  85, 128],
         [ 68,  83, 126],
         ...,
         [121, 126, 104],
         [131, 136, 114],
         [132, 137, 115]],

        [[ 78,  93, 136],
         [ 75,  90, 133],
         [ 68,  83, 126],
         ...,
         [127, 132, 110],
        

In [31]:
cat01.shape

torch.Size([1927, 2370, 3])

In [32]:
cat01.ndim

3

In [33]:
tens01

tensor([0., 0., 0., 0., 0.])

In [34]:
tens02

tensor([1., 1., 1., 1., 1.])

In [36]:
tens01 + 2* tens02

tensor([2., 2., 2., 2., 2.])

In [37]:
a = torch.rand(1_000_000)
b = torch.rand(1_000_000)
c = a + b

In [38]:
c

tensor([0.8300, 1.2928, 0.9869,  ..., 0.7091, 1.2111, 0.9187])

In [39]:
%timeit c = a + b

874 µs ± 197 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [40]:
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
%timeit c_gpu = a_gpu + b_gpu

In [41]:
!pip3 cuda 12.6 install

Traceback (most recent call last):
  File "/bin/pip3", line 11, in <module>
    load_entry_point('pip==20.0.2', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 534, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2930, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2517, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2523, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cl

In [43]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found
